version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tododb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: todo_backend
    restart: always
    depends_on:
      - db
    ports:
      - '4000:4000'
    # This is the part you were asking about
    environment:
      - DB_HOST=db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=tododb

  frontend:
    build:
      context: ./frontend
    container_name: todo_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - '3000:80'

volumes:
  mysql_data: